// COUNTER
export const INCREMENT_COUNT = "INCREMENT_COUNT";
export const DECREMENT_COUNT = "DECREMENT_COUNT";

// AUTH
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// BOOKMARK
export const ADD_PAGE = "ADD_PAGE";
export const DELETE_PAGE = "DELETE_PAGE";
export const UPDATE_PAGE = "UPDATE_PAGE";
export const SET_PAGES = "SET_PAGES";
export const SET_PAGE = "SET_PAGE";
export const SELECTED_PAGE = "SELECTED_PAGE";

// COLLECTIONS
export const ADD_COLLECTION = "ADD_COLLECTION";
export const DELETE_COLLECTION = "DELETE_COLLECTION";
export const UPDATE_COLLECTION = "UPDATE_COLLECTION";

// URL
export const ADD_URL = "ADD_URL";
export const DELETE_URL = "DELETE_URL";
export const UPDATE_URL = "UPDATE_URL";